apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app: web-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
        containers:
        - name: web-nginx
          image: registry.wtransnet.local:5000/sistemas/web-nginx:latest
#          image: registry.wtransnet.local:5000/webserver/web-nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /var/www
            name: pvc-web-nginx-www
          - mountPath: /mnt/nfs
            name: pvc-web-nginx-nfs
          - mountPath: /etc/nginx/sites-enabled
            name: web-nginx-sites-enabled-configmap
        imagePullSecrets:
        - name: registrypullsecret
        volumes:
        - name:  pvc-web-nginx-www
          persistentVolumeClaim:
            claimName:  pvc-web-nginx-www
        - name:  pvc-web-nginx-nfs
          persistentVolumeClaim:
            claimName:  pvc-web-nginx-nfs
        - name: web-nginx-sites-enabled-configmap
          configMap:
            name: web-nginx-sites-enabled-configmap
            items:
            - key: app
              path: app
            - key: www
              path: www
            - key: static
              path: static