apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    app: web-nginx
spec:
 type: NodePort
 ports:
 - port: 80
   # Valid external ports range: 30000-32767
   nodePort: 31050
 selector:
   app: web-nginx