apiVersion: v1
kind: Service
metadata:
  name: wtn-bridge-wtn3
  labels:
    app: wtn-bridge-wtn3
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31003
  selector:
    app: wtn-bridge-wtn3