apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wtn-file-upload
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wtn-file-upload
    spec:   
#        initContainers:
#        - name: postgres-init
#          image: busybox
#          command: ['sh', '-c', 'until nc -w 1 postgres 5432 </dev/null; do echo waiting for postgres UP; sleep 1; done;']
#        - name: redis-init
#          image: busybox
#          command: ['sh', '-c', 'until nc -w 1 redis 6379 </dev/null; do echo waiting for redis UP; sleep 1; done;']
#        - name: rabbitmq-init
#          image: busybox
#          command: ['sh', '-c', 'until nc -w 1 rabbitmq 5672 </dev/null; do echo waiting for rabbitmq UP; sleep 1; done;']
        containers:
        - name: wtn-file-upload
          image: registry.wtransnet.local:5000/java8-1/wtn-file-upload:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shared-configmap
            - configMapRef:
                name: wtn-file-upload-configmap
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-wtn-file-upload-nfs
          - mountPath: /docker/gradle_user_home/wtn-auth
            name: pvc-wtn-file-upload-gradle          
          - mountPath: /git
            name: pvc-wtn-file-upload-git
        volumes:
          - name: pvc-wtn-file-upload-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-nfs
          - name: pvc-wtn-file-upload-gradle
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-gradle
          - name: pvc-wtn-file-upload-git
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-git
        imagePullSecrets:
        - name: registrypullsecret
        volumes:
          - name: pvc-wtn-file-upload-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-nfs
          - name: pvc-wtn-file-upload-gradle
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-gradle
          - name: pvc-wtn-file-upload-git
            persistentVolumeClaim:
              claimName: pvc-wtn-file-upload-git
        imagePullSecrets:
        - name: registrypullsecret 