apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gluster-master-config
  labels:
    etiqueta: pv-gluster-master-config
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-9177a7c03-2a67010cbab59391-int-pv-gluster-master-config"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-master-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-gluster-master-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gluster-master-data
  labels:
    etiqueta: pv-gluster-master-data
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-8c47a7c03-9ee7010cba659391-int-pv-gluster-master-data"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-master-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-gluster-master-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gluster-master-etc
  labels:
    etiqueta: pv-gluster-master-etc
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-94d7a7c03-45c7010cbae59391-int-pv-gluster-master-etc"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-master-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-gluster-master-etc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gluster-master-logs
  labels:
    etiqueta: pv-gluster-master-logs
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-9777a7c03-ec07010cbb159391-int-pv-gluster-master-logs"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-master-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-gluster-master-logs
