apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wtn-audit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wtn-audit
    spec:
        initContainers:
        - name: postgres-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 postgres 5432 </dev/null; do echo waiting for postgres UP; sleep 1; done;']
        - name: rabbitmq-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 rabbitmq 5672 </dev/null; do echo waiting for rabbitmq UP; sleep 1; done;']
        containers:
        - name: wtn-audit
          image: registry.wtransnet.local:5000/java8-1/wtn-audit:latest
          imagePullPolicy: Always
          command:
          - sleep
          - "3600"
          envFrom:
            - configMapRef:
                name: shared-configmap
            - configMapRef:
                name: wtn-audit-configmap
            - secretRef:
                name: shared-secret
            - secretRef:
                name: wtn-audit-secret
          livenessProbe:
            httpGet:
              path: /audit/private/actuator/health/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-wtn-audit-nfs
        volumes:
          - name: pvc-wtn-audit-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-audit-nfs
        imagePullSecrets:
        - name: registrypullsecret