apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-restore-volume-data
  labels:
    etiqueta: pv-restore-volume-data
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-e397a7c03-fec7010cd14593e5-int-pv-redis-master-data"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-restore-volume-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-restore-volume-data