apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-geo-searcher-nfs
  labels:
    etiqueta: pv-wtn-geo-searcher-nfs
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /docker/volumes/nfs/pv-nfs-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-geo-searcher-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-geo-searcher-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-geo-searcher-gradle
  labels:
    etiqueta: pv-wtn-geo-searcher-gradle
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /docker/gradle_user_home/wtn-geo-searcher
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-geo-searcher-gradle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-geo-searcher-gradle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-geo-searcher-git
  labels:
    etiqueta: pv-wtn-geo-searcher-git
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /git/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-geo-searcher-git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-geo-searcher-git