apiVersion: v1
kind: Service
metadata:
  name: postgres-pg2
  labels:
    app: postgres-pg2
spec:
 type: NodePort
 ports:
 - port: 5432
   name : postgres-pg2
   # Valid external ports range: 30000-32767
   nodePort: 30433
 selector:
   app: postgres-pg2
