apiVersion: v1
kind: Service
metadata:
  name: wtn-integration
  labels:
    app: wtn-integration
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31000
  selector:
    app: wtn-integration