#
# Jetty Logging Module
#   Output Managed by Logback
#
# It was dynamically generated by Chef on appint02.wtransnet.local
#
# Local modifications will be overwritten by Chef.
#

[name]
logging

[depend]
resources

[lib]
/usr/local/jetty/lib/logging/*.jar

[files]
logs/
/usr/local/jetty/lib/logging/slf4j-api-1.6.6.jar
/usr/local/jetty/lib/logging/logback-core-1.0.7.jar
/usr/local/jetty/lib/logging/logback-classic-1.0.7.jar
/usr/local/jetty/resources/logback.xml
/usr/local/jetty/resources/jetty-logging.properties