apiVersion: v1
kind: Service
metadata:
  name: wtn-push
  labels:
    app: wtn-push
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31010
  selector:
    app: wtn-push