apiVersion: v1
kind: Service
metadata:
  name: web-nginx-wtn-tracking-web
  labels:
    app: web-nginx-wtn-tracking-web
spec:
 type: NodePort
 ports:
 - port: 80
   # Valid external ports range: 30000-32767
   nodePort: 31081
 selector:
   app: web-nginx-wtn-tracking-web
