apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci
  labels:
    app: jenkins
spec:
 type: NodePort
 ports:
 - port: 8080
   name : jenkins
   # Valid external ports range: 30000-32767
   nodePort: 31082
 selector:
   app: jenkins