apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-data
  namespace: ci
  labels:
    etiqueta: pv-jenkins-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: "192.168.6.81:3260"
    iqn: "iqn.2001-05.com.equallogic:0-8a0906-0ac7a7c03-3a27010dde9598d7-pro-pv-jenkins-data"
    lun: 0
    fsType: "ext4"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jenkins-data
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      etiqueta: pv-jenkins-data