apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
 type: NodePort
 ports:
 - port: 5672
   name : rabbitmq
   # Valid external ports range: 30000-32767
 - port: 15672
   nodePort: 30072
   name : rabbitmq-ui
 selector:
   app: rabbitmq