apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cron-data
  labels:
    etiqueta: pv-cron-data
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/docker/volumes/cron/pv-cron-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cron-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-cron-data