apiVersion: v1
kind: Service
metadata:
  name: cron
  labels:
    app: cron
spec:
  type: NodePort
  ports:
  - port: 22
    # Valid external ports range: 30000-32767
    nodePort: 30673
  selector:
    app: cron