apiVersion: v1
kind: Service
metadata:
  name: wtn-tracking
  labels:
    app: wtn-tracking
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31006
  selector:
    app: wtn-tracking