apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-bridge-wtn3-nfs
  labels:
    etiqueta: pv-wtn-bridge-wtn3-nfs
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /docker/volumes/nfs/pv-nfs-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-bridge-wtn3-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-bridge-wtn3-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-bridge-wtn3-gradle
  labels:
    etiqueta: pv-wtn-bridge-wtn3-gradle
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /docker/gradle_user_home/wtn-bridge-wtn3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-bridge-wtn3-gradle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-bridge-wtn3-gradle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-bridge-wtn3-git
  labels:
    etiqueta: pv-wtn-bridge-wtn3-git
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /git/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-bridge-wtn3-git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-bridge-wtn3-git