apiVersion: v1
kind: Service
metadata:
  name: postgres-pg1
  labels:
    app: postgres-pg1
spec:
 type: NodePort
 ports:
 - port: 5432
   name : postgres-pg1
   # Valid external ports range: 30000-32767
   nodePort: 30432
 selector:
   app: postgres-pg1
