apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wtn-email-nfs
  labels:
    etiqueta: pv-wtn-email-nfs
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  glusterfs:
    path: vol01
    endpoints: glusterfs-cluster
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wtn-email-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-wtn-email-nfs