apiVersion: v1
kind: Service
metadata:
  name: wtn-email
  labels:
    app: wtn-email
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31007
  selector:
    app: wtn-email