apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wtn-email
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wtn-email
    spec:   
        initContainers:
        - name: rabbitmq-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 rabbitmq 5672 </dev/null; do echo waiting for rabbitmq UP; sleep 1; done;']
#        - name: gluster-init
#          image: busybox
#          command: ['sh', '-c', 'until nc -w 1 glusterfs-cluster 1 </dev/null; do echo waiting for gluster UP; sleep 1; done;']
        containers:
        - name: postfix
          image: registry.wtransnet.local:5000/sistemas/postfix:latest
          imagePullPolicy: Always   
          env:
          - name: HOSTNAME #Se usa para configurar el postfix side container
            value: "wtn-email.wtransnet.com"
          envFrom:
            - configMapRef:
                name: shared-configmap
        - name: wtn-email
          image: registry.wtransnet.local:5000/java8-1/wtn-email:latest
          imagePullPolicy: Always
#          command:
#          - sleep
#          - "3600"
          envFrom:
            - configMapRef:
                name: shared-configmap
            - configMapRef:
                name: wtn-email-configmap
            - secretRef:
                name: shared-secret
            - secretRef:
                name: wtn-email-secret
          livenessProbe:
            httpGet:
              path: /email/private/actuator/health/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-wtn-email-nfs
        volumes:
          - name: pvc-wtn-email-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-email-nfs
        imagePullSecrets:
        - name: registrypullsecret