apiVersion: v1
kind: Service
metadata:
  name: wtn-geo-searcher
  labels:
    app: wtn-geo-searcher
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31004
  selector:
    app: wtn-geo-searcher