apiVersion: v1
kind: Service
metadata:
  name: wtn-credit
  labels:
    app: wtn-credit
spec:
  type: NodePort
  ports:
  - port: 8080
    # Valid external ports range: 30000-32767
    nodePort: 31005
  selector:
    app: wtn-credit