apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-busybox-exports
  labels:
    etiqueta: pv-busybox-exports
  annotations:
    volume.beta.kubernetes.io/mount-options: "-o vers=3"
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.98.206.232
    path: /exports
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-busybox-exports
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      etiqueta: pv-busybox-exports