apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wtn-integration
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wtn-integration
    spec:
        initContainers:
        - name: postgres-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 postgres 5432 </dev/null; do echo waiting for postgres UP; sleep 1; done;']
        containers:
        - name: wtn-integration
          image: registry.wtransnet.local:5000/java8-1/wtn-integration:latest
          imagePullPolicy: Always
#          command:
#          - sleep
#          - "3600"
          envFrom:
            - configMapRef:
                name: shared-configmap
            - configMapRef:
                name: wtn-integration-configmap
            - secretRef:
                name: shared-secret
            - secretRef:
                name: wtn-integration-secret
          livenessProbe:
            httpGet:
              path: /integration/private/actuator/health/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-wtn-integration-nfs
        volumes:
          - name: pvc-wtn-integration-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-integration-nfs
        imagePullSecrets:
        - name: registrypullsecret

