apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
 type: NodePort
 ports:
 - port: 6379
   # Valid external ports range: 30000-32767
   nodePort: 30079
 selector:
   app: redis