apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-nginx-wtn-adm-web
  labels:
    app: web-nginx-wtn-adm-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-nginx-wtn-adm-web
    spec:
#        initContainers:
#        - name: gluster-init
#          image: busybox
#          command: ['sh', '-c', 'until nc -w 1 glusterfs-cluster 1 </dev/null; do echo waiting for gluster UP; sleep 1; done;']
        containers:
        - name: web-nginx
#          image: registry.wtransnet.local:5000/frontend/web-nginx-wtn-adm-web:latest
          image: registry.wtransnet.local:5000/sistemas/web-nginx:latest
          imagePullPolicy: Always
#          command:
#          - sleep
#          - "3600"
          ports:
          - containerPort: 80
#          livenessProbe:
#            httpGet:
#              path: /index.html
#              port: 80
#              scheme: HTTP
#            initialDelaySeconds: 60
#            timeoutSeconds: 3
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-web-nginx-wtn-adm-web-nfs
          - mountPath: /etc/nginx/sites-enabled
            name: web-nginx-wtn-adm-web-sites-enabled-configmap
        - name: nginx-vts-exporter
          image: sophos/nginx-vts-exporter:latest
          env:
          - name: NGINX_STATUS
            value: "http://localhost/status/format/json"
          - name: METRICS_ENDPOINT
            value: "/metrics"
          - name: METRICS_ADDR
            value: ":9913"
          ports:
          - containerPort: 9913
        imagePullSecrets:
        - name: registrypullsecret
        volumes:
        - name:  pvc-web-nginx-wtn-adm-web-nfs
          persistentVolumeClaim:
            claimName:  pvc-web-nginx-wtn-adm-web-nfs
        - name: web-nginx-wtn-adm-web-sites-enabled-configmap
          configMap:
            name: web-nginx-wtn-adm-web-sites-enabled-configmap
            items:
            - key: app
              path: app
            - key: www
              path: www
            - key: static
              path: static
