apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wtn-email
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wtn-email
    spec:   
        initContainers:
        - name: postgres-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 postgres 5432 </dev/null; do echo waiting for postgres UP; sleep 1; done;']
        - name: redis-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 redis 6379 </dev/null; do echo waiting for redis UP; sleep 1; done;']
        - name: rabbitmq-init
          image: busybox
          command: ['sh', '-c', 'until nc -w 1 rabbitmq 5672 </dev/null; do echo waiting for rabbitmq UP; sleep 1; done;']
        containers:
        - name: wtn-email
          image: registry.wtransnet.local:5000/java8-1/wtn-email:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shared-configmap
            - configMapRef:
                name: wtn-email-configmap
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /mnt/nfs
            name: pvc-wtn-email-nfs
        volumes:
          - name: pvc-wtn-email-nfs
            persistentVolumeClaim:
              claimName: pvc-wtn-email-nfs
        imagePullSecrets:
        - name: registrypullsecret